### ISSUE TITLE
compilation error on ubuntu 20.04

### ISSUE THREAD

**Issue by altineller** [nepluno/SoapFilm3D#6]
Hello,
I am trying to compile on ubuntu 20.04. I am sure I have installed the deps, but here is the error log that I get:

/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/textures/beach.h:18073:45: warning: null character(s) ignored
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/textures/beach.h:18073:47: warning: null character(s) ignored
In file included from /home/can/bin/SoapFilm3D/Apps/SoapFilm3D/PRRenderer.cpp:13:
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/textures/beach.h:1:5: error: ‘p’ does not name a type
    1 | ��# p r a g m a   o n c e   
      |     ^
In file included from /home/can/bin/SoapFilm3D/Apps/SoapFilm3D/PRRenderer.cpp:13:
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/textures/beach.h:18073:8: error: expected unqualified-id before ‘/’ token
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/PRRenderer.cpp: In member function ‘bool PRRenderer::create_cube_map(GLuint&)’:
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/PRRenderer.cpp:232:32: error: ‘texture’ has not been declared
  232 |                                texture::beach::bottom,
      |                                ^~~~~~~
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/PRRenderer.cpp:233:39: error: ‘texture’ has not been declared
  233 |                                sizeof(texture::beach::bottom));
      |                                       ^~~~~~~
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/PRRenderer.cpp:237:26: error: ‘texture’ has not been declared
  237 |                          texture::beach::top, sizeof(texture::beach::top));
      |                          ^~~~~~~
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/PRRenderer.cpp:237:54: error: ‘texture’ has not been declared
  237 |                          texture::beach::top, sizeof(texture::beach::top));
      |                                                      ^~~~~~~
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/PRRenderer.cpp:241:26: error: ‘texture’ has not been declared
  241 |                          texture::beach::front, sizeof(texture::beach::front));
      |                          ^~~~~~~
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/PRRenderer.cpp:241:56: error: ‘texture’ has not been declared
  241 |                          texture::beach::front, sizeof(texture::beach::front));
      |                                                        ^~~~~~~
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/PRRenderer.cpp:245:26: error: ‘texture’ has not been declared
  245 |                          texture::beach::back, sizeof(texture::beach::back));
      |                          ^~~~~~~
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/PRRenderer.cpp:245:55: error: ‘texture’ has not been declared
  245 |                          texture::beach::back, sizeof(texture::beach::back));
      |                                                       ^~~~~~~
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/PRRenderer.cpp:249:26: error: ‘texture’ has not been declared
  249 |                          texture::beach::left, sizeof(texture::beach::left));
      |                          ^~~~~~~
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/PRRenderer.cpp:249:55: error: ‘texture’ has not been declared
  249 |                          texture::beach::left, sizeof(texture::beach::left));
      |                                                       ^~~~~~~
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/PRRenderer.cpp:253:26: error: ‘texture’ has not been declared
  253 |                          texture::beach::right, sizeof(texture::beach::right));
      |                          ^~~~~~~
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/PRRenderer.cpp:253:56: error: ‘texture’ has not been declared
  253 |                          texture::beach::right, sizeof(texture::beach::right));
      |                                                        ^~~~~~~
make[2]: *** [Apps/SoapFilm3D/CMakeFiles/SoapFilm3D.dir/build.make:128: Apps/SoapFilm3D/CMakeFiles/SoapFilm3D.dir/PRRenderer.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:160: Apps/SoapFilm3D/CMakeFiles/SoapFilm3D.dir/all] Error 2
make: *** [Makefile:84: all] Error 2

It  complains about beach.h and then quits.

Best Regards,
Can

**Comment by raymondyfei** [comment]
I cannot reproduce this issue on Ubuntu 20.04. Which version of GCC are you using? Also `SoapFilm3D/Apps/SoapFilm3D/textures/beach.h` doesn't have line 18073.

**Comment by altineller** [comment]
gcc version 9.4.0 (Ubuntu 9.4.0-1ubuntu1~20.04.1) 

I think something is going wrong processing the beach.h file:

/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/textures/beach.h:2733:65: warning: null character(s) ignored
 2733 |          0 x c 0 ,   0 x 2 1 ,   0 x 8 e ,   0 x a 0 ,   0 x 9 2 ,   0 x 7 a ,   0 x c 4 ,   0 x 6 8 ,   0 x 2 4 ,   0 x 9 e ,   0 x 3 b ,   0 x 8 b ,   
      |                                                                 ^
/home/can/bin/SoapFilm3D/Apps/SoapFilm3D/textures/beach.h:2733:67: warning: null character(s) ignored
 2733 |          0 x c 0 ,   0 x 2 1 ,   0 x 8 e ,   0 x a 0 ,   0 x 9 2 ,   0 x 7 a ,   0 x c 4 ,   0 x 6 8 ,   0 x 2 4 ,   0 x 9 e ,   0 x 3 b ,   0 x 8 b , 

I logged the make output, which produced 127mb of errors, so I am attaching it as a zipfile.

[log.txt.gz](https://github.com/nepluno/SoapFilm3D/files/8422238/log.txt.gz)

**Comment by raymondyfei** [comment]
There seems to be some weird file encoding issue. Should be fixed by the latest commit.

**Comment by altineller** [comment]
I confirm with latest commit, the issue is fixed, and it compiles.
